// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using Foundation;
using UIKit;
using WeatherSampleOne.Config;
using WeatherSampleOne.Services.Factory;
using WeatherSampleOne.ViewModels;
using Xamarin.Essentials;

namespace WeatherSampleOne.iOS
{
	public partial class WeatherResultViewController : UIViewController
	{
		WeatherSearchViewModel viewModel;

		public WeatherResultViewController (IntPtr handle) : base (handle)
		{
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            viewModel = ServiceFactory.Resolve<WeatherSearchViewModel>();

            if (viewModel.TheWeatherResponse != null)
            {
                //WeatherDescriptionLabel.Text = $"{viewModel.TheWeatherResponse.Weather?.FirstOrDefault()?.Description}";
                List<string> theDescriptions = viewModel.TheWeatherResponse.Weather?.Select(s => s.Description).ToList();
                WeatherDescriptionLabel.Text = $"{string.Join("\n", theDescriptions)}";
                TemperaturesDescriptionLabel.Text = $"{viewModel.TheWeatherResponse.Main.Temp}K";
            }
            SaveCityAndGoBackButton.TouchUpInside += SaveCityAndGoBackButton_TouchUpInside;
            GoBackButton.TouchUpInside += GoBackButton_TouchUpInside;
        }

        private void SaveCityAndGoBackButton_TouchUpInside(object sender, EventArgs e)
        {
            Preferences.Set(Constants.FAVOURITE_CITY, viewModel.TheWeatherRequest?.City);
            this.NavigationController.PopViewController(true);
        }

        private void GoBackButton_TouchUpInside(object sender, EventArgs e)
        {
            this.NavigationController.PopViewController(true);
        }
    }
}
