// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WeatherSampleOne.iOS
{
	public partial class WeatherResultViewController : UIViewController
	{
		public WeatherResultViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
